# Generated by Django 3.2.8 on 2021-12-25 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lodestone_id', models.TextField()),
                ('name', models.CharField(max_length=60)),
                ('token', models.CharField(max_length=40)),
                ('verified', models.BooleanField(default=False)),
                ('world', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
