# Generated by Django 3.2.8 on 2021-12-29 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gear'),
    ]

    operations = [
        migrations.CreateModel(
            name='BISList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bis_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_body_set', to='api.gear')),
                ('bis_bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_bracelet_set', to='api.gear')),
                ('bis_earrings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_earrings_set', to='api.gear')),
                ('bis_feet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_feet_set', to='api.gear')),
                ('bis_hands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_hands_set', to='api.gear')),
                ('bis_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_head_set', to='api.gear')),
                ('bis_left_ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_left_ring_set', to='api.gear')),
                ('bis_legs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_legs_set', to='api.gear')),
                ('bis_mainhand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_mainhand_set', to='api.gear')),
                ('bis_necklace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_necklace_set', to='api.gear')),
                ('bis_offhand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_offhand_set', to='api.gear')),
                ('bis_right_ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_right_ring_set', to='api.gear')),
                ('current_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_body_set', to='api.gear')),
                ('current_bracelet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_bracelet_set', to='api.gear')),
                ('current_earrings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_earrings_set', to='api.gear')),
                ('current_feet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_feet_set', to='api.gear')),
                ('current_hands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_hands_set', to='api.gear')),
                ('current_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_head_set', to='api.gear')),
                ('current_left_ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_left_ring_set', to='api.gear')),
                ('current_legs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_legs_set', to='api.gear')),
                ('current_mainhand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_mainhand_set', to='api.gear')),
                ('current_necklace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_necklace_set', to='api.gear')),
                ('current_offhand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_offhand_set', to='api.gear')),
                ('current_right_ring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_right_ring_set', to='api.gear')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bis_lists', to='api.character')),
            ],
            options={
                'ordering': ['-job__role', '-job__ordering'],
                'unique_together': {('job', 'owner')},
            },
        ),
    ]
