# Generated by Django 3.2.8 on 2022-01-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bis_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_item_level', models.IntegerField()),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'ordering': ['-max_item_level'],
            },
        ),
    ]
