# Generated by Django 3.2.10 on 2022-01-09 23:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invite_code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tier')),
            ],
        ),
    ]
