# Generated by Django 3.2.10 on 2022-01-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='raid_gear_name',
            field=models.TextField(default='Asphodelos'),
            preserve_default=False,
        ),
    ]
