# Generated by Django 3.2.10 on 2022-01-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_loot_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bislist',
            options={'ordering': ['-job__role', 'job__ordering']},
        ),
    ]
