# Generated by Django 3.2.10 on 2022-01-13 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_fix_bis_list_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loot',
            options={'ordering': ['-obtained', '-id']},
        ),
        migrations.AddField(
            model_name='loot',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
        migrations.AlterField(
            model_name='loot',
            name='obtained',
            field=models.DateField(),
        ),
    ]
