# Generated by Django 3.2.10 on 2022-01-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_updated_fields_on_loot'),
    ]

    operations = [
        migrations.AddField(
            model_name='bislist',
            name='external_link',
            field=models.URLField(null=True),
        ),
    ]
