# Generated by Django 3.2.11 on 2022-01-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='notifications',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='settings',
            name='theme',
            field=models.CharField(max_length=24),
        ),
    ]
