# Generated by Django 3.2.11 on 2022-02-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='tome_gear_name',
            field=models.TextField(default='Augmented Radiant Host'),
            preserve_default=False,
        ),
    ]
