# Generated by Django 3.2.12 on 2022-05-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_tome_augment_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alias',
            field=models.CharField(default='', max_length=64),
        ),
    ]
