# Generated by Django 3.2.13 on 2022-05-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_character_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='bislist',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='bislist',
            unique_together=set(),
        ),
    ]
