# Generated by Django 3.2.13 on 2022-06-19 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_multi_bis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loot_manager', models.BooleanField(default=False)),
                ('team_characters', models.BooleanField(default=False)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.teammember')),
            ],
        ),
    ]
