# Generated by Django 3.2.14 on 2022-08-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_team_proxy_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='permissions',
            field=models.IntegerField(default=0),
        ),
    ]
