# Generated by Django 3.2.19 on 2023-07-27 15:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_loot_manager_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tier',
            name='fights',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
