# Generated by Django 3.2.24 on 2024-05-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_tier_fight_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='solver_sort_overrides',
            field=models.JSONField(default=dict),
        ),
    ]
