# Generated by Django 3.2.24 on 2024-06-08 14:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_team_override_solver_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='extra_import_classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=None),
        ),
        migrations.AddField(
            model_name='gear',
            name='extra_import_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=list, size=None),
        ),
    ]
