# Generated by Django 3.2.25 on 2024-10-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_using_auto_prefetch'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='loot_solver_greed',
            field=models.BooleanField(default=False),
        ),
    ]
