# Generated by Django 4.2.30 on 2026-04-28 10:44

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_greedability_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='XIVVersion',
            fields=[
                ('version', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['-version'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
