# docker-compose.yml
version: '3'
services:
  database:
    image: "postgres:13"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts downvolumes:
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  proxy:
    image: 'nginx:latest'
    volumes:
      - './nginx-local.conf:/etc/nginx/conf.d/default.conf'
    network_mode: host

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

volumes:
  database-data: # named volumes can be managed easier using docker-compose
