[tool.poetry]
name = "savage-aim-backend"
version = "20260513"
description = "Django Backend for savageaim.com"
authors = ["freyama.de"]
license = "MIT"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
django = "4.2.30"
djangorestframework = "3.15.2"
django-allauth = "0.50.0"
drf-spectacular = "0.27.2"
django-auto-prefetch = "1.9.0"
psycopg2-binary = "2.9.3"
channels-redis = "3.4.0"
channels = "3.0.4"
jellyfish = "0.9.0"
beautifulsoup4 = "4.10.0"
coreapi = "2.3.3"
setuptools = "^75.6.0"
sentry-sdk = "^2.58.0"
redis = "4.5.5"
django-cloud-tasks = "^0.0.4"

[tool.poetry.group.cors]
optional = true

[tool.poetry.group.cors.dependencies]
django-cors-headers = "^4.9.0"

[tool.poetry.group.wsgi]
optional = true

[tool.poetry.group.wsgi.dependencies]
gunicorn = "^25.3.0"

[tool.poetry.group.testing]
optional = true

[tool.poetry.group.testing.dependencies]
coverage = "^7.13.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
