<template>
  <div>
    <div class="card-header">
      <div class="card-header-title">
        Changelog
      </div>
      <div class="card-header-icon">
        <a @click="() => { this.$emit('close') }" class="icon">
          <i class="material-icons">close</i>
        </a>
      </div>
    </div>
    <div class="card-content content">
      <h2 class="has-text-primary subtitle">{{ version }}</h2>
      <div class="divider"><i class="material-icons icon">expand_more</i> FFXIV 7.01 Update <i class="material-icons icon">expand_more</i></div>
      <p>
        Added the following new types of Gear released in 7.01;
        <ul>
          <li>Light-heavy Armour and Accessories - Item Level 710</li>
        </ul>
      </p>

      <div class="divider"><i class="material-icons icon">expand_more</i> XIVGear Support <i class="material-icons icon">expand_more</i></div>
      <p>You can now also import BIS data from XIVGear.app</p>
      <p>If you provide a URL that contains multiple sets, you will be prompted with a popup to select which one to load.</p>
      <p class="has-text-info">Please note that this feature is only on the main BIS pages, the quick signup form can only handle single set URLs!</p>

      <div class="divider"><i class="material-icons icon">expand_more</i> Dalamud Plugin <i class="material-icons icon">expand_more</i></div>
      <p>I am happy to announce that the Dalamud plugin that was teased in the last release is finally up and ready to use.</p>
      <p>Currently, it must be installed as a custom plugin repo due to Dalamud Team's build systems being on hold</p>
      <p>The code and installation instructions are located <a href="https://github.com/SavageAim/plugin" target="_blank">here!</a></p>
      <p>If there are any questions or issues, please report them as you would anything with the website itself!</p>

      <div class="divider"><i class="material-icons icon">expand_more</i> API Schema <i class="material-icons icon">expand_more</i></div>
      <p>In the last release, API Keys were added to allow external access for possibly building an ecosystem of tools.</p>
      <p>However, it only dawned on me recently that the API isn't obvious for anyone other than me.</p>
      <p>There is now an OpenAPI schema available at <a href="https://savageaim.com/backend/schema/" target="_blank">https://savageaim.com/backend/schema/</a>.</p>
      <p>This set of documentation is mostly manually written so if there are any questions, feel free to ask on Discord/Github!</p>

      <div class="divider"><i class="material-icons icon">expand_more</i> Fixes &amp; Improvements <i class="material-icons icon">expand_more</i></div>
      <p>Fixed a bug causing the popup generated by the "Add New" button on the Team Membership forms to not display any information.</p>
      <p>Improved fetching of Teams from the database to improve speed and lessen the load on the server.</p>
      <p>Added "API Schema" and "Plugin" links to the footer icons.</p>
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'

@Component
export default class Changelog extends Vue {
  get version(): string {
    return this.$store.state.version
  }
}
</script>

<style lang="scss">
</style>
