name: Docker Image CI

on:
  release:
    types:
      - published

jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file deployment/Dockerfile -t ghcr.io/savageaim/app/backend:latest -t ghcr.io/savageaim/app/backend:$(echo "$GITHUB_REF" | sed 's/refs\/tags\///')
    - name: Login to GitHub Docker Registry
      run: docker login ghcr.io -u freyamade -p ${{ secrets.GITHUB_TOKEN }}
    - name: Push the Docker image
      run: docker push --all-tags ghcr.io/savageaim/app/backend

  build-ws-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file deployment/ws.Dockerfile -t ghcr.io/savageaim/app/ws-backend:latest -t ghcr.io/savageaim/app/ws-backend:$(echo "$GITHUB_REF" | sed 's/refs\/tags\///')
    - name: Login to GitHub Docker Registry
      run: docker login ghcr.io -u freyamade -p ${{ secrets.GITHUB_TOKEN }}
    - name: Push the Docker image
      run: docker push --all-tags ghcr.io/savageaim/app/ws-backend

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file deployment/Dockerfile --tag ghcr.io/savageaim/app/frontend:latest -t ghcr.io/savageaim/app/frontend:$(echo "$GITHUB_REF" | sed 's/refs\/tags\///')
    - name: Build maintenance image
      run: docker build . --file deployment/Dockerfile --build-arg VUE_APP_MAINTENANCE="1" --tag ghcr.io/savageaim/app/frontend:maint
    - name: Login to GitHub Docker Registry
      run: docker login ghcr.io -u freyamade -p ${{ secrets.GITHUB_TOKEN }}
    - name: Push the Docker image
      run: docker push --all-tags ghcr.io/savageaim/app/frontend
